const MENU_ITEMS = [
  { name: "Thepla (4 pcs)", price: 50, img: "images/menu-thepla.jpeg" },
  { name: "Poha", price: 25, img: "images/menu-poha.jpeg" },
  { name: "Kota Special Kachori (1 pc)", price: 25, img: "images/menu-kachori.jpeg" },
  { name: "Khamaan (100g)", price: 40, img: "images/menu-khamaan.jpeg" },
  { name: "Upma", price: 35, img: "images/menu-upma.jpeg" },
  { name: "Idli Sambhar", price: 80, img: "images/menu-idli sambhar.jpeg" },
  { name: "Paratha (4 pcs)", price: 60, img: "images/menu-paratha.jpg" },
  { name: "Masala Dosa", price: 75, img: "images/menu-dosa.avif" },
  { name: "Fafda (100g)", price: 65, img: "images/menu-Fafda.jpg" },
  { name: "Oats", price: 99, img: "images/menu-oats.avif" },
  { name: "Vadapav", price: 35, img: "images/menu-Vadapav.jpg" },
  { name: "Samosa (2 pcs)", price: 35, img: "images/menu-samosa.webp" },
  { name: "Paneer Butter Masala (250g)", price: 170, img: "images/menu-paneerbutter.jpeg" },
  { name: "Palak Paneer (250g)", price: 180, img: "images/menu-palakpaneer.jpg" },
  { name: "Malai Kofta (250g)", price: 180, img: "images/menu-malaikofta.webp" },
  { name: "Veg. Handi Brown (250g)", price: 165, img: "images/menu-veghandi.jpg" },
  { name: "Dal Fry (250g)", price: 120, img: "images/menu-dalfry.jpeg" },
  { name: "Dal Tadka (250g)", price: 150, img: "images/menu-daltadka.jpeg" },
  { name: "Jeera Rice", price: 95, img: "images/menu-jeerarice.webp" },
  { name: "Cheese Biryani", price: 185, img: "images/menu-cheesebiryani.jpeg" },
  { name: "Butter Fulka Roti", price: 17, img: "images/menu-roti.jpeg" },
  { name: "Bajra ka Rotlo", price: 69, img: "images/menu-rotlo.webp" },
  { name: "Butter Naan", price: 65, img: "images/menu-naan.jpg" },
  { name: "Butter Tawa Paratha", price: 45, img: "images/menu-lachhaparatha.jpeg" },
  { name: "Chole Bhature (2 pcs)", price: 180, img: "images/menu-cholebhatore.jpeg" },
  { name: "Pav Bhaji (3 pcs)", price: 170, img: "images/menu-pavbhaji.jpeg" },
  { name: "Bhel", price: 45, img: "images/menu-bhel.jpeg" },
  { name: "Katchi Dabeli", price: 30, img: "images/menu-katchiddabeli.jpeg" },
  { name: "Paneer Chilli", price: 180, img: "images/menu-paneerchilly.jpeg" },
  { name: "Veg. Steamed Momos (5 pcs)", price: 150, img: "images/menu-momos.jpg" },
  { name: "Dal Pakwan", price: 75, img: "images/menu-dal pakwan.jpeg" },
  { name: "Veg. Dry Manchurian", price: 185, img: "images/menu-manchurian.jpeg" }
];

